***All Training and Testing is performed in Google Colab***<br>
***CSV file submitted contains data from model 1 that is from keras bold tex***t 

In [1]:
from google.colab import drive
drive.mount('/content/drive')

Go to this URL in a browser: https://accounts.google.com/o/oauth2/auth?client_id=947318989803-6bn6qk8qdgf4n4g3pfee6491hc0brc4i.apps.googleusercontent.com&redirect_uri=urn%3Aietf%3Awg%3Aoauth%3A2.0%3Aoob&scope=email%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdocs.test%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fdrive.photos.readonly%20https%3A%2F%2Fwww.googleapis.com%2Fauth%2Fpeopleapi.readonly&response_type=code

Enter your authorization code:
··········
Mounted at /content/drive


In [2]:
!ls "/content/drive/My Drive"

 1111552		    A1_024_ass1.txt		     p4.py
 815384-TAG5FG.part01.rar   a.cpp			     p5.py
 815384-TAG5FG.part02.rar  'Anikesh Pal Resume.pdf'	     p6.py
 815384-TAG5FG.part03.rar  'Anikesh Resume.gdoc'	     p7.py
 815384-TAG5FG.part04.rar   bnkacc.cpp			     p8.py
 815384-TAG5FG.part05.rar   Classroom			     p9.py
 815384-TAG5FG.part06.rar  'Colab Notebooks'		     Pics
 815384-TAG5FG.part07.rar  'hitkul(sample_submission).csv'   p.py
 815384-TAG5FG.part08.rar   lists-expertise-gdoc.gdoc	     stack1.c
 815384-TAG5FG.part09.rar  'My Books'			     stack2345.c
 815384-TAG5FG.part10.rar   p10.py			     stck.cpp
 815384-TAG5FG.part11.rar   p11.py			     test_image.pkl
 815384-TAG5FG.part12.rar   p1.py			     train_image.pkl
 815384-TAG5FG.part13.rar   p2.py			     train_label.pkl
 A1_019_ass3.sh		    p3.py


**Method 1 :- Using Keras (Deep Learning)**

Train Accuracy ~ 99%<br>
Test Accuracy ~ 80%.<br>
Train and Test split :- 87.5%(7000 points) and 100-87.5%(1000 points) respectively.<br>
Epochs :- 200<br>
Two Hidden Layer has been used of dimensions 512 and 128.<br>
Weight Initialisation is done using Random Normal by Xavier/Glorot<br>
Activation Function Used :- ReLU and Softmax<br>
Optimizer Used :- Adam<br>

In [112]:
#Retrieving data and modifying it
import pickle
import numpy as np
with open(r'drive/My Drive/train_image.pkl','rb') as f:
    image0=pickle.load(f)
print(len(image0))
print(len(image0[0]))
with open(r'drive/My Drive/train_label.pkl','rb') as f1:
    label0=pickle.load(f1)
print(len(label0))
with open(r'drive/My Drive/test_image.pkl','rb') as f2:
    image_test0=pickle.load(f2)
print(len(image_test0))
print(len(image_test0[0]))
#converting Training and Test data into numpy arrays
image=np.array(image0)
label=np.zeros((8000,4),dtype=int)
#One hot encoding of labels
for i in range(0,8000):
    if label0[i]==2:
        label[i][0]=1
    if label0[i]==3:
        label[i][1]=1
    if label0[i]==0:
        label[i][2]=1
    if label0[i]==6:
        label[i][3]=1
image_test=np.array(image_test0)

8000
784
8000
2000
784


In [113]:
print(image.shape)

(8000, 784)


Normalisation of Data

In [0]:
#Normalisation/Standardisation
image=image/255
image_test=image_test/255

In [115]:
from keras.utils import np_utils
from keras.initializers import RandomNormal
from keras.models import Sequential
from keras.layers import Dense, Activation
from keras.layers.normalization import BatchNormalization
print(label[3000])

[1 0 0 0]


In [0]:
#Variable Initialisation
output_dim=4
input_dim=image.shape[1]
batch_size=100
np_epoch=200

In [0]:
#Data Splitting
from sklearn.model_selection import train_test_split
img1,img2,lbl1,lbl2=np.array(train_test_split(image,label,test_size=1-0.875))

Model Training and Fitting

In [118]:
#MODEL
model_relu=Sequential()
model_relu.add(Dense(512,activation='relu',input_shape=(input_dim,),kernel_initializer=RandomNormal(mean=0.0,stddev=0.062,seed=None)))
model_relu.add(BatchNormalization())
model_relu.add(Dense(128,activation='relu',kernel_initializer=RandomNormal(mean=0.0,stddev=0.125,seed=None)))
model_relu.add(BatchNormalization())
model_relu.add(Dense(output_dim,activation='softmax'))
print(model_relu.summary())
model_relu.compile(optimizer='adam',loss='categorical_crossentropy',metrics=['accuracy'])
model_relu.fit(img1,lbl1,batch_size=batch_size,epochs=np_epoch,verbose=1,validation_data=(img2,lbl2)) 
y_new=model_relu.predict_classes(image_test) 
for i in range(1500,1550):
    if y_new[i]==0:
        print("Image_test:",i,"-->Predicted=2")
    if y_new[i]==3:
        print("Image_test:",i,"-->Predicted=6")
    if y_new[i]==2:
        print("Image_test:",i,"-->Predicted=0")
    if y_new[i]==1:
        print("Image_test:",i,"-->Predicted=3")

_________________________________________________________________
Layer (type)                 Output Shape              Param #   
dense_19 (Dense)             (None, 512)               401920    
_________________________________________________________________
batch_normalization_13 (Batc (None, 512)               2048      
_________________________________________________________________
dense_20 (Dense)             (None, 128)               65664     
_________________________________________________________________
batch_normalization_14 (Batc (None, 128)               512       
_________________________________________________________________
dense_21 (Dense)             (None, 4)                 516       
Total params: 470,660
Trainable params: 469,380
Non-trainable params: 1,280
_________________________________________________________________
None
Train on 7000 samples, validate on 1000 samples
Epoch 1/200
7000/7000 [==============================] - 4s 504us/step - loss: 

Adam Optimizer is used here as iit gives adaptive learning rate giving better results

In [0]:
#Creating CSV File 
import pandas as pd
lst=[]
for i in range(2000):
    if y_new[i]==0:
        lst.append(2)
    if y_new[i]==3:
        lst.append(6)
    if y_new[i]==2:
        lst.append(0)
    if y_new[i]==1:
        lst.append(3)
d={'Test_image_index':range(len(lst)),'predicted class':lst}
df=pd.DataFrame(d)
df.to_csv('Anikesh_Pal.csv',encoding='utf-8',index=False)

In [0]:
from google.colab import files
files.download('Anikesh_Pal.csv')

Count of each class label

In [121]:
#Counting Class Labels
print(lst.count(0))
print(lst.count(2))
print(lst.count(3))
print(lst.count(6))

515
509
462
514


**Method 2 :- Using TensorFlow (Deep Learning)**

Accuracy :- 83.30%.<br>
Train and Test split :- 87.5%(7000 points) and 100-87.5%(1000 points) respectively.<br>
Epochs :- 200<br>
Two Hidden Layer has been used of dimensions 512 and 128.<br>
Weight Initialisation is done using Random Normal by Xavier/Glorot<br>
Activation Function Used :- Sigmoid and Softmax<br>
Optimizer Used :- Adam<br>

In [128]:
#Data Retrieval
import pickle
import numpy as np
with open(r'drive/My Drive/train_image.pkl','rb') as f:
    image0=pickle.load(f)
print(len(image0))
print(len(image0[0]))
with open(r'drive/My Drive/train_label.pkl','rb') as f1:
    label0=pickle.load(f1)
print(len(label0))
with open(r'drive/My Drive/test_image.pkl','rb') as f2:
    image_test0=pickle.load(f2)
print(len(image_test0))
print(len(image_test0[0]))
#COnverting data to numpy arrays and labels to one hot encoded numpy array
image=np.array(image0)
label=np.zeros((8000,4),dtype=int)
for i in range(0,8000):
    if label0[i]==2:
        label[i][0]=1
    if label0[i]==3:
        label[i][1]=1
    if label0[i]==0:
        label[i][2]=1
    if label0[i]==6:
        label[i][3]=1
image_test=np.array(image_test0)

8000
784
8000
2000
784


In [0]:
from sklearn.model_selection import train_test_split
img1,img2,lbl1,lbl2=np.array(train_test_split(image,label,test_size=1-0.875))

In [0]:
n_hidden_1=512
n_hidden_2=128
n_input=784
n_classes=4

Weight and Bias Initialization

In [0]:
import tensorflow as tf
import numpy as np
training_epochs=200
learning_rate=0.001
batch_size=100
x=tf.placeholder(tf.float32,[None,784])
y_=tf.placeholder(tf.float32,[None,4])
#Initialising Weights and biases
weights_relu={
    'h1':tf.Variable(tf.random_normal([n_input,n_hidden_1],stddev=0.062,mean=0)),
    'h2':tf.Variable(tf.random_normal([n_hidden_1,n_hidden_2],stddev=0.125,mean=0)),
    'out':tf.Variable(tf.random_normal([n_hidden_2,n_classes],stddev=0.120,mean=0))
}
biases={
    'b1':tf.Variable(tf.random_normal([n_hidden_1])),
    'b2':tf.Variable(tf.random_normal([n_hidden_2])),
    'out':tf.Variable(tf.random_normal([n_classes]))
}

Defining Multiple Perceptron Layer

In [0]:
#Defining Layers
def multilayer_perceptron(x,weights,biases):
    print('x:',x.get_shape(),'W[h1]:',weights['h1'].get_shape(),'b[h1]:',biases['b1'].get_shape())
    layer_1=tf.add(tf.matmul(x,weights['h1']),biases['b1'])
    layer_1=tf.nn.sigmoid(layer_1)
    print('layer_1:',layer_1.get_shape(),'W[h2]:',weights['h2'].get_shape(),'b[h2]:',biases['b2'].get_shape())
    layer_2=tf.add(tf.matmul(layer_1,weights['h2']),biases['b2'])
    layer_2=tf.nn.sigmoid(layer_2)
    print('layer_2:',layer_2.get_shape(),'W[out]:',weights['out'].get_shape(),'b3:',biases['out'].get_shape())
    out_layer=tf.matmul(layer_2, weights['out'])+biases['out']   
    out_layer=tf.nn.sigmoid(out_layer)
    print('out_layer:',out_layer.get_shape())
    return out_layer

Model Trainning and prediction

In [133]:
y_adam=multilayer_perceptron(x,weights_relu,biases)
cost_adam=tf.reduce_mean(tf.nn.softmax_cross_entropy_with_logits(logits=y_adam,labels=y_))
optimizer_adam=tf.train.AdamOptimizer(learning_rate=learning_rate).minimize(cost_adam)
total_batch=int(len(image)/batch_size)
with tf.Session() as sess:
    tf.global_variables_initializer().run()
    for epoch in range(training_epochs):
        sess.run([optimizer_adam,cost_adam,weights_relu],feed_dict={x:img1,y_:lbl1})
    lstx=sess.run(tf.argmax(y_adam,1),feed_dict={x:image_test})
    correct_prediction=tf.equal(tf.argmax(y_adam,1),tf.argmax(y_,1))
    accuracy=tf.reduce_mean(tf.cast(correct_prediction, tf.float32))
    print("Accuracy:", accuracy.eval({x:img2,y_:lbl2}))

x: (?, 784) W[h1]: (784, 512) b[h1]: (512,)
layer_1: (?, 512) W[h2]: (512, 128) b[h2]: (128,)
layer_2: (?, 128) W[out]: (128, 4) b3: (4,)
out_layer: (?, 4)
Accuracy: 0.833


In [0]:
lstx1=[]
for i in range(len(lstx)):
    if lstx[i]==2:
        lstx1.append(0)
    if lstx[i]==3:
        lstx1.append(6)
    if lstx[i]==1:
        lstx1.append(3)
    if lstx[i]==0:
        lstx1.append(2)

Count of each class label

In [135]:
print(lstx1.count(0))
print(lstx1.count(2))
print(lstx1.count(3))
print(lstx1.count(6))

499
534
506
461


**Method 3 :- Using Logistic Regression**

Accuracy :- 80.40%.<br>
Train and Test split :- 87.5%(7000 points) and 100-87.5%(1000 points) respectively.<br>
Epochs :- 500<br>
Solver Used :- LBFGS

In [146]:
#Data Retreival
import pickle
import numpy as np
with open(r'drive/My Drive/train_image.pkl','rb') as f:
    image0=pickle.load(f)
print(len(image0))
print(len(image0[0]))
with open(r'drive/My Drive/train_label.pkl','rb') as f1:
    label0=pickle.load(f1)
print(len(label0))
with open(r'drive/My Drive/test_image.pkl','rb') as f2:
    image_test0=pickle.load(f2)
print(len(image_test0))
print(len(image_test0[0]))
#Converting data to numpy array
image=np.array(image0)
label=np.array(label0)
image_test=np.array(image_test0)

8000
784
8000
2000
784


In [147]:
print(label.shape)

(8000,)


Normalisation of data

In [0]:
image=image/255
image_test=image_test/255

Data Splitting into training and testing for checking accuracy

In [0]:
from sklearn.model_selection import train_test_split
img1,img2,lbl1,lbl2=np.array(train_test_split(image,label,test_size=1-0.875))

Model Training and Predicting

In [150]:
from sklearn.linear_model import LogisticRegression
logReg=LogisticRegression(solver='lbfgs',max_iter=500)
logReg.fit(img1,lbl1)
lst=logReg.predict(image_test)

/usr/local/lib/python3.6/dist-packages/sklearn/linear_model/logistic.py:460: FutureWarning: Default multi_class will be changed to 'auto' in 0.22. Specify the multi_class option to silence this warning.
  "this warning.", FutureWarning)


Accuracy calculation

In [151]:
print(logReg.score(img2,lbl2))

0.804


In [0]:
import pandas as pd
image_test_pd=pd.DataFrame(image_test)
lst1= list(lst)

Count of each class label

In [153]:
print(lst1.count(0))
print(lst1.count(2))
print(lst1.count(3))
print(lst1.count(6))

518
538
500
444
